### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8081/api/v1/events
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJnZEBnbWFpbC5jb20iLCJpYXQiOjE3ODY0MzQ5OTksImV4cCI6MTc4NjUyMTM5OX0.sVAt7a42B2zWb62mPQNuUHj5i7GnY6cNQOZYqf-X0fxSLdIn4Fk5fwHTDlWtSZl0
Content-Type: application/json

{
    "title": "Java Spring Boot Workshop",
    "description": "A hands-on workshop",
    "eventDateTime": "2026-09-15T10:00:00",
    "capacity": 100,
    "category": "TECH",
    "price": 499.0,
    "venueId": 1
}