###
POST http://localhost:8081/auth/register
Content-Type: application/json

{
    "name": "Goureesh",
    "email": "goureesh@gmail.com",
    "password": "Password@123",
    "phoneNumber": "9876543210"
}
###
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "goureesh@gmail.com",
  "password": "Password@123"
}