###
POST http://localhost:8081/auth/register
Content-Type: application/json

{
    "name": "GD",
    "email": "gd@gmail.com",
    "password": "Password@123",
    "phoneNumber": "9876543219"
}
###
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "gd@gmail.com",
  "password": "Password@123"
}